{% set name = "otumat" %}
{% set version = "0.3.0" %}

# test message1
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7fb8a28016f061c8b0570260ee3c17a5719d67beb9cd8b4edd5dae56e98218f9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - cryptography
    - flask
    - appdirs
    - watchdog
  run:
    - python >=3.6
    - cryptography
    - flask
    - appdirs
    - watchdog
test:
  imports:
    - otumat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/datajoint/otumat
  summary: A suite of maintainer tools and utilities for pip packages.
  description: |
    Otumat (pronounced "Automate") is a suite of maintainer tools and utilities for pip packages.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/datajoint/otumat

extra:
  recipe-maintainers:
    - guzman-raphael
